# Generated by Django 4.1.3 on 2023-02-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('ja', 'Japanese')], default='ru', max_length=10),
        ),
    ]
